alias much="cd"
alias very="cd"
alias so="cd"
alias many="cd"
alias pls="cd"
alias wow="cd ~/"
alias gptd="gksudo gparted"
alias ins="sudo apt-get install"
alias rep="sudo apt-add-repository"
alias komodo="exec /home/riley/Komodo-Edit-8/lib/mozilla/komodo"
alias mo="sudo mount /dev/sda2 /media/windows"
alias um="sudo umount /dev/sda2"
alias screenfetch="/home/riley/Downloads/screenfetch-dev"
alias cw="cd ~/git/python/codewars/"
alias tmuxtest="tmux -2 -c 'cd ~/git/python/'"
alias finc="export TERM=xterm && finch"
alias rain.sh="~/./Downloads/rain.sh/rain.sh"
