#!/bin/bash

ORIG=$(pwd)

echo "adding repositories"
echo ""
sudo apt-add-repository -y ppa:versable/elementary-update
sudo apt-add-repository -y ppa:numix/ppa
sudo apt-add-repository -y ppa:vincent-c/ponysay
sudo apt-add-repository -y ppa:ingalex/super-boot-manager
sudo apt-add-repository -y ppa:n-muench/burg
sudo apt-add-repository -y ppa:richardgv/compton
sudo apt-add-repository -y ppa:no1wantdthisname/ppa
sudo echo "deb http://debian.sur5r.net/i3/ raring universe" >> /etc/apt/sources.list
echo ""
echo ""
echo "updating and upgrading"
echo ""

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -f -y install
sudo apt-get -y upgrade

sudo apt-get install -y libqtgui
sudo apt-get -f -y install
sudo apt-get install -y libqtgui

sudo dpkg -i skype-ubuntu-precise_4.2.0.13-1_i386.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo dpkg -i dropbox_1.6.0_amd64.deb
sudo dpkg -i google-musicmanager-beta_current_amd64.deb

sudo apt-get install -y i3
sudo apt-get install -y git
sudo apt-get install -y vim-gtk

sudo apt-get install -y rxvt-unicode-256color xterm elementary-tweaks indicator-synapse etube gazette nuvolaplayer elementary-lion-theme elementary-champagne-theme elementary-blue-theme elementary-thirdparty-icons elementary-plank-themes elementary-wallpaper-collection linux-generic-lts-trusty ncmpcpp mpd mpdscribble gimp libreoffice mpc apt-file dmenu ponysay gconf-editor unetbootin dconf-tools gstreamer0.10-ffmpeg gstreamer0.10-plugins-bad qt4-qtconfig gparted smbfs zip unzip tmux mtr slurm ttyrec htop iotop iftop iptraf nethogs ack calcurse remind wyrd newsbeuter rsstail tig qalc finch pidgin-data pidgin-skype blender fontconfig-infinality numix-gtk-theme numix-icon-theme-circle numix-plank-theme gftp

wget http://git.silverirc.com/cgit.cgi/screenfetch.git/plain/screenfetch-dev
sudo chmod +x screenfetch-dev

#Configure Git
git config --global user.name "Asonix"
git config --global user.email "asonix.dev@gmail.com"

#Install fun terminal things
cd ~/Downloads
git clone https://github.com/livibetter/pipes.sh.git
cd pipes.sh
sudo make install
cd ..
git clone https://github.com/livibetter/pipesX.sh.git
cd pipesX.sh
sudo make install
cd ..
git clone https://gist.github.com/5933594.git
mv 5933594 rain.sh

#Install non
sudo apt-get install -y libjpeg-dev jack jack2 liblo-dev libsndfile1-dev ladspa-sdk liblrdf0-dev libsigc++-2.0-dev 
git clone git://git.tuxfamily.org/gitroot/non/non.git
sudo chmod -R 777 non
cd non
git submodule update --init
cd lib/ntk
sudo ./waf configure
sudo ./waf
sudo ./waf install
cd ~/Downloads/non
sudo ./waf configure
sudo ./waf
sudo ./waf install
cd ..

#Install patched i3 and depends
git clone https://github.com/DSMan195276/i3.git
cd i3
git checkout dsm-changes
sudo apt-get install -y sur5r-keyring libx11-xcb-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb1-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxrandr-dev libxcb-randr0-dev libev-dev libxcb-xinerama0-dev libxcursor-dev compton xterm rxvt-unicode-256color xfonts-terminus i3status libanyevent-i3-perl libanyevent-perl libcommon-sense-perl libconfuse-common libconfuse0 libjson-xs-perl libxcb-cursor0 libxcb-dpms0 libxcb-image0 libxcb-render-util0 libxkbcommon0 suckless-tools libxcb-cursor-dev libxcb-keysyms1-dev --allow-unauthenticated
make
sudo make install
sudo apt-get remove i3
cd ..

cd $ORIG

mkdir ~/.i3
mkdir ~/.mpd
mkdir ~/.mpd/playlists
mkdir ~/.ncmpcpp

touch ~/.mpd/mpd.log
touch ~/.mpd/mpdstate
touch ~/.mpd/sticker.sql
touch ~/.mpd/mpd.db
touch ~/.mpd/mpd.pid

cp i3config ~/.i3/config
cp mpdconf ~/.mpd/mpd.conf
cp ncmpcppconfig ~/.ncmpcpp/config
cp xresources ~/.Xresources
cp switcher.py ~/switcher.py
cp i3statusconf ~/.i3status.conf
cp i3statussh ~/.i3status.sh
cp bash_aliases	~/.bash_aliases
cp vimrc ~/.vimrc
cp tmuxconf ~/.tmux.conf
cp gntrc ~/.gntrc
cp update ~/.update
cp xswitcher.py ~/xswitcher.py
cp resizeL.py ~/resizeL.py
cp resizeS.py ~/resizeS.py
cp compton.conf ~/.config/compton.conf

sudo apt-get install burg burg-themes super-boot-manager
sudo burg-install "(hd0)"

wget http://www.deviantart.com/download/187228213/el_castillo_burg_theme_by_bigrza-d33gy7p.zip

mkdir burg
unzip el_castillo_burg_theme_by_bigrza-d33gy7p.zip -d burg
sudo cp -r burg/El_Castillo /boot/burg/themes/
sudo cp white_elementary.png /boot/burg/themes/white/
sudo update burg
sudo burg-emu -D
echo "press t"
apt-file udpate
sudo bash /etc/fonts/infinality/infctl.sh setstyle
